### ISSUE TITLE
Question about observation list in karpathy_game.py

### ISSUE THREAD

**Issue by jazzsaxmafia** [nivwusquorum/tensorflow-deepq#17]
Hello, I am a newbie in Reinforcement Learning, and I thought this project is a wonderful resource to learn RL.

I have been going through your source code, and the line
https://github.com/nivwusquorum/tensorflow-deepq/blob/master/tf_rl/simulation/karpathy_game.py#L202
is kind of confusing for me.

From my understanding, each observation of hero's line consists of
[ type_of_object (wall/friend/enemy), object_speed (x,y), dist_from_hero ] 
so the type_of_object should be something like [0,1,0], [1,0,0] or [0,0,1]
in the source code I attached, however, it assigns [1,1,1], and that sounds like it treats all types (wall/friend/enemy) equally.

Is it my misunderstanding? Please help me understand.
Thank you.

-Taeksoo

**Comment by IronChariot** [comment]
Hi Taeksoo,

My understand of the input from each observation line is this:
The first three numbers (in the case where there are only enemies, friends
and walls) are the normalised distance between the hero and the first
object/wall the sight line hits. By default they are 1, meaning that there
is no object/wall intersecting the sight line. When, say, a wall starts to
intersect the sight line, the 'distance to wall' for that line gets reduced
at that point, so instead of getting [1, 1, 1, ...] you get [1, 1, 0.99,
...] and so on as the wall gets closer.
If you look at the karpathy game notebook, I think there is a bit at the
bottom where it takes a moment from the training that you ran and shows you
an example observation - this may help clarify what the inputs are and how
they work for specific situations.

Regards,
Sam
