### ISSUE TITLE
high dimension states

### ISSUE THREAD

**Issue by animalelement865** [nivwusquorum/tensorflow-deepq#8]
Great project! I'm looking to use this with a Kinect v2 camera for a robotics application. I have 26 different joints each with x,y,z coordinates that will be my state space. Looking through the code it looks like the state it just a single int. Can you give me some guidance on how to feed in all these states? 

I know with standard qlearning you have a S-A pair which are both just a single value. Is it possible to have 3 actions. In my example it would be motor 1, motor 2, motor 3.

**Comment by siemanko** [comment]
Hi Saasier,

Sounds like a very exciting project! Keep me updated! 

As far as the algorithm I wrote is concerned it only allows for discrete actions, i.e. you have to have a reasonably sized set of actions (the smaller the better, but anything >200 is unlikely to work) and on every timestep you need to pick exactly one of these actions (example actions could be UP, DOWN, LEFT, RIGHT). In general that often does not play well with robot motion control applications because the action space for robots is infinite (you can choose the torque of each of the motors which is a real number), or very large when reasonably quantized (as it increases exponentially in the number of motors). That's why people tend to use actor-critic models (recent work by deep mind: http://arxiv.org/pdf/1509.02971v2.pdf) or different techniques altogether (check out work by Sergey Levine as well as Russ Tedrake's work). 

I personally have tried implementing the continuous method by deep mind ("continuous" branch of this repo), but failed to make it converge for even the simplest scenarios. I suspect it is due to software bug, but I did not have time to thoroughly debug it yet. 

Szymon

**Comment by siemanko** [comment]
PS. There was also a bit of a discussion about it on reddit. https://www.reddit.com/r/MachineLearning/comments/3ytnqc/deep_q_learning_with_continuous_actions_question/

**Comment by siemanko** [comment]
PS2. In my answer I assumed you meant action instead of state. My state is actually quite high dimensional. For example in Karpathy's Game notebook you can see at the bottom a visualization of all the numbers in the state vector (32 \* 6 + 2 = 194 numbers).

**Comment by animalelement865** [comment]
https://www.youtube.com/watch?v=Bwv_wJbEbVE - here's the application. It's a robot you physically stand in front of and box. This was at the RoboUniverse show in San Diego a few weeks ago. Positive reward if the robot punches the user, negative reward if the user punches the robot. It's using SARSA right now and the states are gestures detected by a machine learning algorithm that Microsoft made (Visual Gesture Builder). The problem is that I have to create and tag all those states and a lot of nuance is obviously lost. States are things like elbows out, step left, step right, etc.   

I think that by feeding all the joint data into tensor I'll get better action selection. Right now the actions are discrete and are pre-programmed sequences of moves, (left straight, right hook, left upper cut) or (left straight, right straight, left straight, right straight). I can continue to stay with this but I thought it might be fun to watch the robot learn how to throw punches. 

Back to the state question, maybe I'm blind here but I'm still not seeing where to pass the states in. I'm looking at the Karpathy Game example.

**Comment by animalelement865** [comment]
Damn, there's no Windows support in tensorflow. I'm using Unity3d with the Kinect 2 and that only works on Windows.

**Comment by siemanko** [comment]
I've seen some researchers around mit using kinect over linux though... Not sure about unity, but maybe unity is not needed? You can also try to set-up remote linux server with tensorflow, which is just for learning.
